version: '3'
services:
  nextcloudpi:
    image: ownyourbits/nextcloudpi-armhf
    command: "${IP}"
    ports:
     - "80:80"
     - "443:443"
     - "4443:4443"
    volumes:
     - ncdata:/data
     - /etc/localtime:/etc/localtime:ro
    container_name: nextcloudpi

volumes:
  ncdata:
